### ISSUE TITLE
Not a recognized storage provider

### ISSUE THREAD

**Issue by gjaldon** [dwilkie/carrierwave_direct#116]
When I set `config.storage = :file`, I get the `not a recognized storage provider` error. This happens in both dev and test environments.

As a work-around, I tried using `Fog.mock!` for my test environment but I keep getting an error in `upload_directly` when it clicks the button "Upload evidence". The error I get is: `ActionController::RoutingError: No route matches [POST] "/"`. When I check it on dev, it works fine. Maybe something wrong with how I set-up `Fog.mock!`?

Here's how I set up `Fog.mock!`:
```ruby
#spec/support/fog.rb
Fog.mock!

connection = ::Fog::Storage.new(
  :aws_access_key_id => Figaro.env.aws_access_key_id,
  :aws_secret_access_key => Figaro.env.aws_secret_access_key,
  :region => Figaro.env.aws_s3_region,
  :provider => 'AWS'
)
connection.directories.create(:key => Figaro.env.fog_directory)
```

I used the same fog_credentials for test env in the Fog.mock! as I did for development and production env.

**Comment by p8** [comment]
`config.storage = :file`  doesn't work because CarrierwaveDirect doesn't work with local file storage.

**Comment by atstockland** [comment]
So, if carrierwave directs mission is to direct upload to S3, then how do you test without it?  Im getting the not a recognized storage provider errors too, but if I use the same carrierwave settings in test env as I do in production env it all works.  But, I certainly don't want to be uploading test files to S3.  If this is documented it seems a bit obscure.  What is the fix for running tests with uploaders and CD?

**Comment by hraynaud** [comment]
@p8 what about the fog-local gem. That is valid provider does this gem work with that?

**Comment by p8** [comment]
@hraynaud I don't know if it works with fog-local. It might just work.
