### ISSUE TITLE
Direct Uploading through Controller

### ISSUE THREAD

**Issue by ttseng** [dwilkie/carrierwave_direct#181]
I have a Rails app with a companion mobile application that enables users to upload images and videos to the site.  I'd like to directly upload the media to S3 in the controller (rather than through a form on the website).  How can I do this?

More on this here: http://stackoverflow.com/questions/31172037/h12-request-timeout-error-on-heroku-with-file-uploads

**Comment by fabn** [comment]
If you upload stuff to S3 through controller you'll likely have the same issue, because you'll need to upload the file to your controller and then from heroku temporary storage to S3.

If you need to upload stuff from your mobile app directly to S3 you need to interact directly with S3 bypassing the app completely.
 
You can use this gem methods as helpers to generate signed parameters for file upload with no need to store AWS secrets in the app, but then you'll have to make the request from your mobile app using an HTTP client. Something like this:

```ruby
class DirectUploader < CarrierWave::Uploader::Base
  # Upload them directly to S3
  include CarrierWaveDirect::Uploader
end

class YourModel 
  mount_uploader :image, DirectUploader
end
```

Then you need to create a controller that returns form params to submit the S3 request, e.g.

```ruby
before_action :your_mobile_app_authentication
def upload_params
  @uploader = YourModel.new.image
  @uploader.use_action_status = true
  @uploader.success_action_status = '201' # You can use the http status you prefer here
  respond_to :json
end

def create
  YourModel.create!(key: params[:key])
end

# in view
json.key @uploader.key
json.set! :AWSAccessKeyId, @uploader.aws_access_key_id
json.acl @uploader.acl
json.policy @uploader.policy
json.signature @uploader.signature
json.success_action_status @uploader.success_action_status
```

From your mobile app call the `upload_params` endpoint and get form params, you'll get something like this

```json
{
  "key": "uploads/136158e4-ed59-42f4-bd40-5138c562c3fa/${filename}",
  "AWSAccessKeyId": "your AWS key id",
  "acl": "public-read",
  "policy": "base64 policy string",
  "signature": "request signature",
  "success_action_status": "201"
}
```

Build an HTTP request in your mobile app that submit a form to S3 bucket with those params and file object and if you get a 201 status code in S3 response you have successfully stored a file to S3. You'll get the actual key in S3 response XML (in element `Key`), using that value you can then call the create endpoint to save the database record and have the file attached to it.
